config/routes.rb
require 'routing/access_constraints'

Rails.application.routes.draw do
  default_url_options protocol: :https if Rails.env == 'production'

  get '', to: 'static_pages#choose_locale'

  scope '(:locale)', locale: /en|de|fr|ar/ do
    root 'static_pages#choose_locale'
    get '/start', to: 'static_pages#landing_page', as: :landing_page

    # Password reset
    get '/request_password_reset/new', to: 'password_reset#request_password_reset', as: :request_password_reset
    post '/request_password_reset', to: 'password_reset#create_password_reset'
    get '/reset_password/:id/:token', to: 'password_reset#reset_password', as: :reset_password
    patch '/reset_password', to: 'password_reset#set_new_password'

    get '/index', to: 'maps#index', as: :maps
    post '', to: 'maps#create'
    get '/new', to: 'maps#new', as: :new_map
    get '/needs_unlock', to: 'maps#needs_unlock'

    # Embedded stuff
    scope '/:map_token', constraints: MapAccessRestriction.new do
      get '' , to: 'maps#show', as: :map
      get '/embedded', to: 'maps#show', as: :map_embedded
      get '/edit', to: 'maps#edit', as: :edit_map
      patch '', to: 'maps#update'
      delete '', to: 'maps#destroy', as: :destroy_map
      get '/unlock', to: 'maps#unlock'

      # map static pages
      get '/about' , to: 'maps#about'
      get '/contact' , to: 'messages#new'
      post '/contact' , to: 'messages#create'

      # map categories
      scope '/categories', constraints: CategoriesAccessRestriction.new do
        patch '/:id', to: 'categories#update'
        delete '/:id', to: 'categories#destroy'
        post '/', to: 'categories#create'
        get '/', to: 'categories#index'
      end

      # Map / place ressources
      resources :places, except: [:index, :show], constraints: PlacesAccessRestriction.new do
        resources :descriptions
      end

      # Reviewing, access restriction handled by place ressource access restriction
      get 'places/review_index' , to: 'review#review_index'

      scope '/places/:id' do
        get '/review' , to: 'places_review#review', as: :review_place
        get '/confirm' , to: 'places_review#confirm', as: :confirm_place
        get '/refuse' , to: 'places_review#refuse', as: :refuse_place

        scope '/translation' do
          get '/review' , to: 'translations_review#review', as: :review_translation
          get '/confirm' , to: 'translations_review#confirm', as: :confirm_translation
          get '/refuse' , to: 'translations_review#refuse', as: :refuse_translation
        end
      end

      resources :announcements
      get '/chronicle' , to: 'maps#chronicle'
    end

    # User resources
    resources :users, except: [:destroy, :index, :show, :new]
    get '/sign_up', to: 'users#sign_up', as: :sign_up
    get '/login' , to: 'sessions#new'
    post '/login' , to: 'sessions#create'
    get '/logout' , to: 'sessions#destroy'
    post '/landing_page' , to: 'sessions#create_with_login', as: :create_with_login

    # Admin stuff
    namespace :admin, constraints: AdminConstraint.new do
      get '', to: 'dashboard#index', as: :dashboard
      get '/settings', to: 'settings#edit'
      get '/settings/captcha_system_status', to: 'settings#captcha_system_status'
      patch '/settings', to: 'settings#update'

      get 'users', to: 'users#index', as: :index_users
      delete 'users/:id', to: 'users#destroy', as: :delete_user
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  include Recaptcha::Verify
  include MapAccessGateway # Includes authentication and access restriction methods

  before_action :set_map, except: [:new, :index]
  before_action :allow_iframe_request, only: [:show_embedded, :show]
  before_action :auth_map, if: :needs_to_be_unlocked?, only: [:update, :destroy, :edit]
  before_action :unset_password_if_unchecked, only: [:update]
  after_action :update_visit_timestamp, only: [:show, :update, :edit]

  # Ressources for map unlocking maps via password
  # Return true/false server-side if map is password protected and has not been unlocked yet
  def needs_unlock
    respond_to do |format|
      format.json { render json: { needs_unlock: needs_to_be_unlocked? }.to_json, status: 200 }
    end
  end

  # Unlock server-side, i.e. accept password and add map token to session hash if auth success
  def unlock
    authenticated = @map.authenticated?(attribute: 'password', token: params[:password])
    session[:unlocked_maps].append(request[:map_token]).uniq! if authenticated

    respond_to do |format|
      format.js do
        if unlocked?
          render nothing: true, status: 200
        else
          render nothing: true, status: 401
        end
      end
    end
  end

  # HTTP response does not need to be authenticated as it renders only the template
  # ajax calls
  def show
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @reviewed_places_available = @map.reviewed_places?
    @show_map_description = @map.show_map_description_on_visit && !visited_maps.include?(@map.id)

    visited_maps << @map.id

    respond_to do |format|
      format.json do
        if unlocked?
          render json: {
            places: places_to_show.map(&:geojson),
            categories: @map.category_names.join(',')},
          status: 200
        else
          render nothing: true, status: 401
        end
      end
      format.html do
        if params[:iframe] == 'true'
          render layout: 'iframe/iframe'
        else
          render layout: 'map/map'
        end
      end
    end
  end

  def index
    if @current_user.signed_in?
      @maps = @current_user.maps
    elsif session[:maps].any?
      @maps = session[:maps].map { |id| Map.find(id) }
    else
      redirect_to landing_page_path
    end
  end

  def new
    @map = Map.new
    @url = { action: :create, controller: :maps } # Specify this so map form does commit to correct route...
  end

  def create
    @map = Map.new(map_params)
    @map.user = @current_user unless @current_user.guest?

    if can_commit_to?(model: @map) && @map.save
      session[:maps] << @map.id if @current_user.guest?
      flash[:success] = t('.created')
      redirect_to map_path(@map.secret_token)
    else
      flash.now[:danger] = @map.errors.full_messages.to_sentence
      render :new, status: 400
    end
  end

  def edit
    5.times { @map.categories.build(priority: nil) }
    @url = { action: :update, controller: :maps, map_token: @map.secret_token } # Specify this so map form does commit to correct route...
  end

  def update
    if can_commit_to?(model: @map) && @map.update_attributes(map_params)
      flash[:success] = t('.changes_saved')
      redirect_to map_path(@map.secret_token)
    else
      flash.now[:danger] = @map.errors.full_messages.to_sentence
      5.times { @map.categories.build(priority: nil) }
      @url = { action: :update, controller: :maps, map_token: @map.secret_token_was }
      render :edit, status: 400
    end
  end

  def destroy
    session[:maps]&.delete(@map.id)
    @map.destroy
    flash[:warning] = t('.deleted')
    redirect_to maps_url
  end

  def chronicle
    @announcements = @map.announcements.all.sort_by(&:created_at).reverse
  end

  private

  def visited_maps
    session[:visited_maps] ||= []
  end

  def update_visit_timestamp
    @map.update_attributes(last_visit: Date.today)
  end

  def allow_iframe_request
    response.headers.delete('X-Frame-Options')
  end

  def unset_password_if_unchecked
    @map.update_attributes(password_digest: nil) unless params[:map][:password_protect].present?
  end

  def is_public_token?
    Map.pluck(:public_token).include?(request[:map_token])
  end

  def unlocked?
    is_public_token? ||
      !@map.password_protected? ||
      session[:unlocked_maps].include?(request[:map_token])
  end

  def places_to_show
    (@map.reviewed_places + @map.reviewed_events + items_from_session).uniq
  end

  def is_signed_in?
    return true unless @current_user.guest?
    flash[:error] = t('.need_to_register')
    redirect_to landing_page_url
  end

  def category_attributes
    attributes = %i[id marker_color marker_shape marker_icon_class priority _destroy]
    if @map
      @map.supported_languages.each do |language|
        attributes << "name_#{language}".to_sym
      end
    end
    attributes
  end

  def map_params
    params.require(:map).permit(
      :title,
      :description,
      :show_map_description_on_visit,
      :maintainer_email_address,
      :imprint,
      :is_public,
      :public_token,
      :secret_token,
      :allow_guest_commits,
      :password,
      :password_confirmation,
      :translation_engine,
      :twitter_api_key,
      :twitter_api_secret_key,
      :twitter_access_token,
      :twitter_access_token_secret,
      :twitter_autopost_message,
      :autopost_twitter,
      :twitter_hashtags,
      :max_images_per_place,
      supported_languages: [],
      categories_attributes: category_attributes
    )
  end
end

app/helpers/maps_helper.rb
module MapsHelper
  def is_secret_link?
    Map.find_by(secret_token: request[:map_token]).present?
  end

  def any_maps_available?
    @current_user.registered? || session[:maps].any? 
  end

  # Check if is accessed via map secret link or current user is owner
  def has_privileged_map_access?(map: nil)
    map_in_scope = map || current_map
    map_in_scope&.owned_by?(user: @current_user) || is_secret_link?
  end

  def can_review?
    current_map.allow_guest_commits && has_privileged_map_access?
  end

  def map_token
    request[:map_token]
  end

  def map_access_level(map:)
    if not map.is_public?
      'private-map'
    else
      'public-map'
    end
  end

  def propose_public_token
    if @map.public_token == ('' || nil)
      camelize(@map.title) || SecureRandom.urlsafe_base64(24) 
    else
      @map.public_token
    end
  end

  def camelize(title)
    return nil unless title
    title.gsub!(/[^0-9A-Za-z.\-]/, '_')&.downcase
  end

  def mask(token)
    '*' * 4  + token.slice(token.length - 4, token.length) if token && token.present?
  end

  def twitter_token_encryption_key?
    ENV['TWITTER_TOKEN_ENCRYPTION_PHRASE']
  end
end

app/views/maps/_map.html.haml
= render partial: 'maps/modals/map_description_modal', locals: { map: map }

-# MAP PANEL CONTENT
.col-lg-4.col-md-4
  .panel.panel-default.map-panel

    -# HEADER
    .map-index.panel-heading
      .col-xs-8.map-title{data: { 'map-token' => map.secret_token }}
        = map.title.present? ? map.title : t('.no_title')
      .col-xs-4.map_buttons_container
        %ul.nav.nav-pills.map_buttons
          %li.glyphicon.fa.fa-info-circle.map-modal-button{ data: { target: 'map_description', 'map-id' => map.id}}
          %li.dropdown
            %a.dropdown-toggle.fa.fa-cog.map_settings_button{ 'data-toggle': 'dropdown', href: '#map_settings' }
            %ul.dropdown-menu
              %li= link_to t('.edit_map'), edit_map_url(map_token: map.secret_token)
              %li= link_to t('.delete_map'), map_url(map_token: map.secret_token), method: 'delete', data: { confirm: t('.confirm_delete') }

    -# BODY
    .panel-body
      .content
        - if map.password_protected?
          .map-access-level-container
            .password-protected
              .glyphicon.fa.fa-key.pull-left
              = t('.password_protected')
        .map-access-level-container
          %div{class: map_access_level(map: map)}
            .glyphicon.fa.fa-universal-access.pull-left
            = map.is_public? ? t('.public_map') : t('.private_map')
        .map-access-level-container
          - if map.allow_guest_commits
            .allow_guest_commits
              .glyphicon.fa.fa-pencil.pull-left
              = "#{map.allow_guest_commits? ? t('.guest_commits_allowed') : t('.guest_commits_not_allowed') }"

        .map-specs
          %p
            .glyphicon.fa.fa-map-marker
            = t('.number_of_places', total: map.all_places.count)
            = link_to t('.unreviewed', total: map.unreviewed_places.count), places_review_index_path(map_token: map.secret_token) if map.allow_guest_commits && map.unreviewed_places.any?
          %p
            .glyphicon.fa.fa-calendar
            = t('.number_of_events', total: map.all_events.count)
            = link_to t('.unreviewed', total: map.unreviewed_events.count), places_review_index_path(map_token: map.secret_token) if map.allow_guest_commits && map.unreviewed_events.any?

          %hr
          %p
            .glyphicon.fa.fa-language
              %i= map.supported_languages_string
  .spacer-row

app/views/maps/choose_locale.html.haml
.map-container
  #choose-locale-map
  .overlay.locale-selection-container.text-center
    - I18n.available_locales.each do |l|
      = link_to "/#{l}" do
        .locale-selection
          = t('.select_this_language', locale: l)
:javascript
  jQuery(function() {
    jQuery('.locale-slidepanel').trigger('open');
  });

app/views/maps/edit.html.haml
- content_for :header do
  = t('.edit')

.container
  = render partial: 'maps/form/form'

app/views/maps/index.html.haml
- content_for :header do
  = t('.index')

.container
  - if @current_user.guest?
    .row
      .col-md-12
        .alert.alert-warning
          = t('.session_maps_warning')
          = raw t('.sign_up', link: link_to(t('.here'), sign_up_path))
  .row
    .col-md-12
      .row
        .panel-group
          - if @maps.any?
            = render @maps
          - else
            %p= t('.no_map_yet')

  .row
    .col-md-4
      = link_to t('buttons.create_new_map'), new_map_url, class: 'btn btn-lg btn-success full-width'

app/views/maps/new.html.haml
- content_for :header do
  = t('.new')

.container
  = render partial: 'maps/form/form'

app/views/maps/show.html.haml
.map-container
  #map
  .overlays
    .row
      .col-xs-12.overlay.address-search-bar-container
      .col-xs-12.overlay.confirmation-button-container
        = t('.correct_location?')
        %br
        = button_tag('', type: 'button', class: 'btn btn-success glyphicon glyphicon-ok', id: 'confirmation-button-yes')
        = button_tag('', type: 'button', class: 'btn btn-danger glyphicon glyphicon-remove', id: 'confirmation-button-no')

  = render partial: '/maps/show/map_overlays'
  = render partial: '/maps/show/right_sidebar'
  = render partial: '/maps/show/places_list_panel'
  = render partial: 'maps/modals/map_description_modal', locals: { map: @map }
  = render partial: 'maps/modals/share_map_modal', locals: { map: @map }
  = render partial: 'maps/modals/select_other_locale', locals: { map: @map }

  - if needs_to_be_unlocked?
    = render partial: 'maps/modals/map_password_modal'

  .modal.fade.place-modal
    .modal-dialog
      .modal-content
        .modal-header
          %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
          %h4.modal-title Place
        .modal-body

:javascript
  window.locale = '#{locale}';
  window.map_languages = '#{@map.supported_languages}'
  window.geolocation_error_message_appendix = '#{t('geolocation_error_message_appendix')}';
  window.choose_category = '#{t('choose_category')}';
  window.waiting_for_review_label = '#{t('places.index.waiting_for_review')}';
  window.delete_confirmation_text = '#{t('prompts.confirm_delete')}'
  window.latitude = #{@latitude || 0};
  window.longitude = #{@longitude || 0};
  window.marker_current_position = '#{image_path 'marker/png/marker_current_position.png'}';
  window.placeMarker = '#{image_path 'marker/png/marker_place.png'}';
  window.eventMarker = '#{image_path 'marker/png/marker_event.png'}';
  window.sessionPlaceMarker = '#{image_path 'marker/png/marker_session_place.png'}';
  window.sessionEventMarker = '#{image_path 'marker/png/marker_session_event.png'}';
  window.event_date_range = '#{@map.all_events_date_range}';
  window.map_token = '#{request[:map_token]}'
  window.mapId = #{@map.id}
  window.mayShowMapDescription = #{@show_map_description}

app/views/maps/show_embedded.html.haml
.map-container
  #map
  .overlays
    .row
      .col-xs-12.overlay.address-search-bar-container
      .col-xs-12.overlay.confirmation-button-container
        = t('.correct_location?')
        %br
        = button_tag('', type: 'button', class: 'btn btn-success glyphicon glyphicon-ok', id: 'confirmation-button-yes')
        = button_tag('', type: 'button', class: 'btn btn-danger glyphicon glyphicon-remove', id: 'confirmation-button-no')

  = render partial: '/maps/show/map_overlays'
  = render partial: '/maps/show/right_sidebar'
  = render partial: '/maps/show/places_list_panel'
  = render partial: 'maps/modals/places_index_modal'
  = render partial: 'maps/modals/map_description_modal', locals: { map: @map }

  - if needs_to_be_unlocked?
    = render partial: 'maps/modals/map_password_modal'

  .modal.fade.place-modal
    .modal-dialog
      .modal-content
        .modal-header
          %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
          %h4.modal-title Place
        .modal-body

:javascript
  window.locale = '#{locale}';
  window.map_languages = '#{@map.supported_languages}'
  window.geolocation_error_message_appendix = '#{t('geolocation_error_message_appendix')}';
  window.choose_category = '#{t('choose_category')}';
  window.waiting_for_review_label = '#{t('places.index.waiting_for_review')}';
  window.delete_confirmation_text = '#{t('prompts.confirm_delete')}'
  window.latitude = #{@latitude || 0};
  window.longitude = #{@longitude || 0};
  window.marker_current_position = '#{image_path 'marker/png/marker_current_position.png'}';
  window.placeMarker = '#{image_path 'marker/png/marker_place.png'}';
  window.eventMarker = '#{image_path 'marker/png/marker_event.png'}';
  window.sessionPlaceMarker= '#{image_path 'marker/png/marker_session_place.png'}';
  window.sessionEventMarker= '#{image_path 'marker/png/marker_session_event.png'}';
  window.event_date_range = '#{@map.all_events_date_range}';
  window.map_token = '#{request[:map_token]}'
  window.mapId= #{@map.id}
  window.mayShowMapDescription = #{@show_map_description}