config/routes.rb
require 'routing/access_constraints'

Rails.application.routes.draw do
  default_url_options protocol: :https if Rails.env == 'production'

  get '', to: 'static_pages#choose_locale'

  scope '(:locale)', locale: /en|de|fr|ar/ do
    root 'static_pages#choose_locale'
    get '/start', to: 'static_pages#landing_page', as: :landing_page

    # Password reset
    get '/request_password_reset/new', to: 'password_reset#request_password_reset', as: :request_password_reset
    post '/request_password_reset', to: 'password_reset#create_password_reset'
    get '/reset_password/:id/:token', to: 'password_reset#reset_password', as: :reset_password
    patch '/reset_password', to: 'password_reset#set_new_password'

    get '/index', to: 'maps#index', as: :maps
    post '', to: 'maps#create'
    get '/new', to: 'maps#new', as: :new_map
    get '/needs_unlock', to: 'maps#needs_unlock'

    # Embedded stuff
    scope '/:map_token', constraints: MapAccessRestriction.new do
      get '' , to: 'maps#show', as: :map
      get '/embedded', to: 'maps#show', as: :map_embedded
      get '/edit', to: 'maps#edit', as: :edit_map
      patch '', to: 'maps#update'
      delete '', to: 'maps#destroy', as: :destroy_map
      get '/unlock', to: 'maps#unlock'

      # map static pages
      get '/about' , to: 'maps#about'
      get '/contact' , to: 'messages#new'
      post '/contact' , to: 'messages#create'

      # map categories
      scope '/categories', constraints: CategoriesAccessRestriction.new do
        patch '/:id', to: 'categories#update'
        delete '/:id', to: 'categories#destroy'
        post '/', to: 'categories#create'
        get '/', to: 'categories#index'
      end

      # Map / place ressources
      resources :places, except: [:index, :show], constraints: PlacesAccessRestriction.new do
        resources :descriptions
      end

      # Reviewing, access restriction handled by place ressource access restriction
      get 'places/review_index' , to: 'review#review_index'

      scope '/places/:id' do
        get '/review' , to: 'places_review#review', as: :review_place
        get '/confirm' , to: 'places_review#confirm', as: :confirm_place
        get '/refuse' , to: 'places_review#refuse', as: :refuse_place

        scope '/translation' do
          get '/review' , to: 'translations_review#review', as: :review_translation
          get '/confirm' , to: 'translations_review#confirm', as: :confirm_translation
          get '/refuse' , to: 'translations_review#refuse', as: :refuse_translation
        end
      end

      resources :announcements
      get '/chronicle' , to: 'maps#chronicle'
    end

    # User resources
    resources :users, except: [:destroy, :index, :show, :new]
    get '/sign_up', to: 'users#sign_up', as: :sign_up
    get '/login' , to: 'sessions#new'
    post '/login' , to: 'sessions#create'
    get '/logout' , to: 'sessions#destroy'
    post '/landing_page' , to: 'sessions#create_with_login', as: :create_with_login

    # Admin stuff
    namespace :admin, constraints: AdminConstraint.new do
      get '', to: 'dashboard#index', as: :dashboard
      get '/settings', to: 'settings#edit'
      get '/settings/captcha_system_status', to: 'settings#captcha_system_status'
      patch '/settings', to: 'settings#update'

      get 'users', to: 'users#index', as: :index_users
      delete 'users/:id', to: 'users#destroy', as: :delete_user
    end
  end
end

app/models/place.rb
require 'place/categorizing'
require 'place/geocoding'
require 'place/place_auditing'
require 'place/place_translations_auditing'
require 'place/place_model_helpers'
require 'place/twitter'
require 'validators/custom_validators'
require 'sanitize'

class Place < ActiveRecord::Base
  include Categorizing
  include PlaceTranslationsAuditing
  include PlaceGeocoding
  include PlaceAuditing
  include Sanitization
  include CustomValidators
  include PlaceModelHelpers
  include Twitter

  extend TimeSplitter::Accessors
  split_accessor :start_date
  split_accessor :end_date

  ## ASSOCIATIONS
  belongs_to :map
  has_many :place_category, dependent: :nullify
  has_many :categories, through: :place_category, dependent: :nullify
  has_many :place_attachments, dependent: :destroy
  accepts_nested_attributes_for :place_attachments, reject_if: :all_blank, allow_destroy: true

  ## VALIDATIONS
  validates :name, presence: true
  validates :email, email_format: true, if: 'email.present?'
  validates :phone, phone_number_format: true, if: 'phone.present?'
  validates :homepage, url_format: true, if: 'homepage.present?'
  validates :name, length: { minimum: 3, maximum: 50 }
  validates :place_attachments, respect_quota: true
  validate :end_date, :is_after_start_date?, if: 'start_date.present? && end_date.present?'

  def is_after_start_date?
    if end_date < start_date
      errors.add(:expiration_date, I18n.t('.end_date_before_start_date'))
    end
  end

  def images
    place_attachments.map { |a| ActionController::Base.helpers.image_path(a.image) }
  end

  ## TRANSLATION
  translates :description, versioning: { gem: :paper_trail, options: { on: [:update, :create], only: [:description] } }
  globalize_accessors

  ## CALLBACKS
  geocoded_by :address
  before_validation :sanitize_descriptions, on: [:create, :update]
  after_validation :enforce_ssl_on_urls, on: [:create, :update], if: 'homepage.present?'
  before_create :geocode_with_nodes, unless: 'lat_lon_present?'
  before_update :geocode_with_nodes, if: Proc.new { street_changed? || city_changed? || house_number_changed? || postal_code_changed? }
  after_create :set_description_reviewed_flags
  after_save :set_categories

  # EVENT STUFF
  scope :all_events, -> { where(event: true) }
  scope :ongoing_events, -> { all_events.where("end_date > ? AND start_date < ?", Date.today, Date.today) }
  scope :future_events, -> { all_events.where("start_date > ?", Date.today) }
  scope :past_events, -> { all_events.where("end_date < ?", Date.today) }

  def daterange
    [start_date, end_date].map { |date| date.strftime('%d.%m.%Y %H:%M') if date }.join(' - ')
  end

  def past_event?
    event && end_date < Date.today
  end

  def ongoing_event?
    event && start_date < Date.today && end_date > Date.today
  end

  def future_event?
    event && start_date > Date.today
  end

  ## VIRTUAL ATTRIBUTES
  def address
    address = ["#{street} #{house_number}", "#{postal_code} #{city}"].select { |e| !e.strip.empty? }.join(', ')
    address + " (#{district})" if district
    return address
  end

  # Use this to pass conditional description text (either description itself or information that no translation is present)
  def displayed_description
    reviewed_description.present? ?
      reviewed_description.html_safe :
      I18n.t('.maps.show.places_list_panel.no_description_yet')
  end

  ## MODEL AUDITING
  # Hack categories auditing which is experimental for n:n-relations => audit categories_string, which is DB column
  has_paper_trail on: [:create, :update], ignore: [:reviewed, :description, :categories]

  ## SANITIZE
  def sanitize_descriptions
    I18n.available_locales.each do |locale|
      column = "description_#{locale}"
      send(column + '=', sanitize(send(column)))
    end
  end

  ## PROPERTIES
  def geojson
    {
      id: id,
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [longitude, latitude],
      },
      properties: properties,
      is_event: event,
      start_date: start_date,
      end_date: end_date
    }
  end

  def main_category
    categories&.first
  end

  def properties
    {
      name: name,
      address: address,
      district: district,
      federal_state: federal_state,
      country: country,
      phone: phone,
      email: email,
      homepage: homepage,
      description: displayed_description,
      images: images,
      category_names: categories.map(&:name).map(&:to_s).sort.join(' | '),
      is_event: event,
      reviewed: reviewed,
      marker_color: main_category&.marker_color || 'violet',
      marker_icon_class: main_category&.marker_icon_class,
      marker_shape: main_category&.marker_shape || 'circle',
    }
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  include Recaptcha::Verify
  include MapAccessGateway # Includes authentication and access restriction methods

  before_action :set_map, except: [:new, :index]
  before_action :allow_iframe_request, only: [:show_embedded, :show]
  before_action :auth_map, if: :needs_to_be_unlocked?, only: [:update, :destroy, :edit]
  before_action :unset_password_if_unchecked, only: [:update]
  after_action :update_visit_timestamp, only: [:show, :update, :edit]

  # Ressources for map unlocking maps via password
  # Return true/false server-side if map is password protected and has not been unlocked yet
  def needs_unlock
    respond_to do |format|
      format.json { render json: { needs_unlock: needs_to_be_unlocked? }.to_json, status: 200 }
    end
  end

  # Unlock server-side, i.e. accept password and add map token to session hash if auth success
  def unlock
    authenticated = @map.authenticated?(attribute: 'password', token: params[:password])
    session[:unlocked_maps].append(request[:map_token]).uniq! if authenticated

    respond_to do |format|
      format.js do
        if unlocked?
          render nothing: true, status: 200
        else
          render nothing: true, status: 401
        end
      end
    end
  end

  # HTTP response does not need to be authenticated as it renders only the template
  # ajax calls
  def show
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @reviewed_places_available = @map.reviewed_places?
    @show_map_description = @map.show_map_description_on_visit && !visited_maps.include?(@map.id)

    visited_maps << @map.id

    respond_to do |format|
      format.json do
        if unlocked?
          render json: {
            places: places_to_show.map(&:geojson),
            categories: @map.category_names.join(',')},
          status: 200
        else
          render nothing: true, status: 401
        end
      end
      format.html do
        if params[:iframe] == 'true'
          render layout: 'iframe/iframe'
        else
          render layout: 'map/map'
        end
      end
    end
  end

  def index
    if @current_user.signed_in?
      @maps = @current_user.maps
    elsif session[:maps].any?
      @maps = session[:maps].map { |id| Map.find(id) }
    else
      redirect_to landing_page_path
    end
  end

  def new
    @map = Map.new
    @url = { action: :create, controller: :maps } # Specify this so map form does commit to correct route...
  end

  def create
    @map = Map.new(map_params)
    @map.user = @current_user unless @current_user.guest?

    if can_commit_to?(model: @map) && @map.save
      session[:maps] << @map.id if @current_user.guest?
      flash[:success] = t('.created')
      redirect_to map_path(@map.secret_token)
    else
      flash.now[:danger] = @map.errors.full_messages.to_sentence
      render :new, status: 400
    end
  end

  def edit
    5.times { @map.categories.build(priority: nil) }
    @url = { action: :update, controller: :maps, map_token: @map.secret_token } # Specify this so map form does commit to correct route...
  end

  def update
    if can_commit_to?(model: @map) && @map.update_attributes(map_params)
      flash[:success] = t('.changes_saved')
      redirect_to map_path(@map.secret_token)
    else
      flash.now[:danger] = @map.errors.full_messages.to_sentence
      5.times { @map.categories.build(priority: nil) }
      @url = { action: :update, controller: :maps, map_token: @map.secret_token_was }
      render :edit, status: 400
    end
  end

  def destroy
    session[:maps]&.delete(@map.id)
    @map.destroy
    flash[:warning] = t('.deleted')
    redirect_to maps_url
  end

  def chronicle
    @announcements = @map.announcements.all.sort_by(&:created_at).reverse
  end

  private

  def visited_maps
    session[:visited_maps] ||= []
  end

  def update_visit_timestamp
    @map.update_attributes(last_visit: Date.today)
  end

  def allow_iframe_request
    response.headers.delete('X-Frame-Options')
  end

  def unset_password_if_unchecked
    @map.update_attributes(password_digest: nil) unless params[:map][:password_protect].present?
  end

  def is_public_token?
    Map.pluck(:public_token).include?(request[:map_token])
  end

  def unlocked?
    is_public_token? ||
      !@map.password_protected? ||
      session[:unlocked_maps].include?(request[:map_token])
  end

  def places_to_show
    (@map.reviewed_places + @map.reviewed_events + items_from_session).uniq
  end

  def is_signed_in?
    return true unless @current_user.guest?
    flash[:error] = t('.need_to_register')
    redirect_to landing_page_url
  end

  def category_attributes
    attributes = %i[id marker_color marker_shape marker_icon_class priority _destroy]
    if @map
      @map.supported_languages.each do |language|
        attributes << "name_#{language}".to_sym
      end
    end
    attributes
  end

  def map_params
    params.require(:map).permit(
      :title,
      :description,
      :show_map_description_on_visit,
      :maintainer_email_address,
      :imprint,
      :is_public,
      :public_token,
      :secret_token,
      :allow_guest_commits,
      :password,
      :password_confirmation,
      :translation_engine,
      :twitter_api_key,
      :twitter_api_secret_key,
      :twitter_access_token,
      :twitter_access_token_secret,
      :twitter_autopost_message,
      :autopost_twitter,
      :twitter_hashtags,
      :max_images_per_place,
      supported_languages: [],
      categories_attributes: category_attributes
    )
  end
end

app/helpers/maps_helper.rb
module MapsHelper
  def is_secret_link?
    Map.find_by(secret_token: request[:map_token]).present?
  end

  def any_maps_available?
    @current_user.registered? || session[:maps].any? 
  end

  # Check if is accessed via map secret link or current user is owner
  def has_privileged_map_access?(map: nil)
    map_in_scope = map || current_map
    map_in_scope&.owned_by?(user: @current_user) || is_secret_link?
  end

  def can_review?
    current_map.allow_guest_commits && has_privileged_map_access?
  end

  def map_token
    request[:map_token]
  end

  def map_access_level(map:)
    if not map.is_public?
      'private-map'
    else
      'public-map'
    end
  end

  def propose_public_token
    if @map.public_token == ('' || nil)
      camelize(@map.title) || SecureRandom.urlsafe_base64(24) 
    else
      @map.public_token
    end
  end

  def camelize(title)
    return nil unless title
    title.gsub!(/[^0-9A-Za-z.\-]/, '_')&.downcase
  end

  def mask(token)
    '*' * 4  + token.slice(token.length - 4, token.length) if token && token.present?
  end

  def twitter_token_encryption_key?
    ENV['TWITTER_TOKEN_ENCRYPTION_PHRASE']
  end
end

app/views/maps/modals/_map_description_modal.html.haml
-# DESCRIPTION MODAL
.modal.fade.map-description-modal{role: 'dialog', id: "map_description_#{map.id}"}
  .modal-dialog
    .modal-content
      .modal-header
        %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
        %h4.modal-title= t('.map_description', title: map.title)
      .modal-body
        %p= map.description.present? ? map.description.html_safe : t('.this_map_has_no_description')

app/views/maps/modals/_map_password_modal.html.haml
-# DESCRIPTION MODAL
.modal.fade.map-password-dialog{role: 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title.text-center= t('.map_password')
      .modal-body
        .error-message
        .row
          .col-xs-12
            %input.password-input.pull-left.form-control{ type: 'password' }
        .row
          .col-xs-12.text-center
            %button.unlock.btn.btn-primary.btn-danger= t('buttons.confirm')

app/views/maps/modals/_new_tag_modal.html.haml
-# DESCRIPTION MODAL
.modal.fade.create-map-tags-modal{role: 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
        %h4.modal-title= t('.create_new_tag')
      .modal-body
        -# NEW TAG FORM
        .row
          .col-xs-12
            - map.supported_languages.each do |language|
              .col-md-6.col-xs-12
                %fieldset
                  .input-group
                    %span.input-group-addon= language
                    = text_field_tag :name, '', class: "form-control", data: { attribute: "name_#{language}" }
        .row.button-row
          .col-xs-6.col-sm-4.col-md-3.text-center
            %span.btn.btn-primary.btn-success.create-tag-button{disabled: true}
              = t('buttons.submit')

app/views/maps/modals/_places_index_modal.html.haml
-# Places index modal
= javascript_include_tag 'data_tables.js'

#places-index.modal.fade{role: 'dialog'}
  .modal-dialog
    .modal-content
      .modal-header
        %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
        #search_area
      .modal-body
        .table-container
          %table#places.display.hover.responsive.no-wrap.compact{cellspacing: '0', width: '100%'}
            %thead
              %tr
                %th.all
                %th.all
                  = t('activerecord.attributes.place.name')
                %th.tablet-l.desktop
                  = t('activerecord.attributes.place.start')
                %th.tablet-l.desktop
                  = t('activerecord.attributes.place.end')
                %th.desktop
                  = t('activerecord.attributes.place.address')
                %th.none
                  = t('activerecord.attributes.place.district')
                %th.none
                  = t('.categories')
                %th.none
                  = t('activerecord.attributes.place.email')
                %th.none
                  = t('activerecord.attributes.place.phone')
                %th.none
                  = t('activerecord.attributes.place.homepage')
                %th.none
                  = t('activerecord.attributes.place.description')
            %tbody
              - @reviewed_places_available.each do |place|
                %tr{height: '50px', 'data-categories' => place.category_ids, class: "#{place.event ? 'event' : 'place'}", id: "row_#{place.id}"}
                  %td.place_type_col
                    %span.glyphicon.place_type.pull-left{class: "#{place.event ? 'event fa-calendar' : 'place glyphicon-home'}"}
                  %td.details-control
                    %b= place.name
                  %td
                    = place.start_date if place.start_date
                  %td
                    = place.end_date if place.end_date
                  %td
                    = place.address
                  %td
                    = place.district
                  %td
                    %i= place.category_names
                  %td
                    = place.email
                  %td
                    = place.phone
                  %td
                    = link_to place.homepage, place.homepage
                  %td
                    .description
                      = place.reviewed_description.html_safe
                    - if can_contribute?
                      .place-description-footer
                        - if place.reviewed? && can_contribute?
                          = link_to edit_place_path(place, map_token: request[:map_token]), style: 'text-decoration: none' do
                            %span{class: 'glyphicon glyphicon-pencil'}
                        - else
                          - if @current_user.signed_in?
                            = link_to review_place_path(place, map_token: request[:map_token]), style: 'color: #ff6666; text-decoration: none' do
                              %span{class: 'glyphicon glyphicon-eye-open'}
                          - else
                            %span{class: 'glyphicon glyphicon-eye-open', style: 'color: #AB756B;'}

                        - if @current_user.signed_in?
                          -# = link_to place_path(place, map_token: request[:map_token]), {method: 'delete', data: { confirm: t('.confirm_delete') }} do
                          %span{class: 'glyphicon glyphicon-trash delete-place', place_id: place.id}

app/views/maps/modals/_select_other_locale.html.haml
-# DESCRIPTION MODAL
.modal.fade.select-other-locale{role: 'dialog', "data-keyboard" =>"false", "data-backdrop" =>"static", "data-show" => false}
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title= t('.title')
      .modal-body
        %i= t('.explanation')
        %p
          - @map.supported_languages.each do |language|
            .row
              .col-xs-12
                = link_to t("languages.#{language}"), map_path(map_token: params[:map_token], locale: language)

app/views/maps/modals/_share_map_modal.html.haml
-# SHARE MAP MODAL
.modal.fade.share-map{role: 'dialog', id: "share_map_#{map.id}"}
  .modal-dialog
    .modal-content
      .modal-header
        %span.glyphicon.glyphicon-remove-circle.close{"data-dismiss" => "modal", :type => "button"}
        %h4.modal-title= t('.share_map')
      .modal-body
        .row.margin-below
          .col-xs-12
            %h4
              - if map.is_public?
                %b= t('.public_link')
                %p= link_to map_url(map_token: map.public_token), map_url(map_token: map.public_token)
              - else
                %p= t('.not_a_public_map')

        - if has_privileged_map_access?(map: map)
          .row.margin-below
            .col-xs-12
              %b.red
                = t('.admin_link')
                = " (#{t('.admin_link_warning')})"
              %p= link_to map_url(map_token: map.secret_token), map_url(map_token: map.secret_token)
          %hr

        - if map.is_public?
          .row.margin-below
            .col-xs-12
              %h4
                %b= t('.embed_map_via_iframe')
              %code
                = "<iframe src=" + '"' + "#{root_url}/#{map.public_token}/embedded?iframe=true" + '"' + ' width="600" height="600"></iframe>'